### ISSUE TITLE
Question about LED

### ISSUE THREAD

**Issue by dimmu311** [reverieline/CC2538-CC2592-ZNP#1]
Hi, this is not realy a issu,
it is just a question.

I use your Firmware on CC2538-CC2592 Chip with pcb from https://modkam.ru/?p=1112#more-1112.
i had flashed MODKAMRU_V3_USB.hex.
The pcb had led connected to PB1..4.
in your patchfile i see you als defined leds on this ports. After plug to my control system led on PB1 to 3 lights up. about 1 second later only PB1 lights up.
now, when i control zigbee device no other led lights up. So my question is, is this the normal behavior for now? 
Anyway i'm not sure at the moment if your firmware uses PB1..4 oder PB0..3?

Tank you

**Comment by reverieline** [comment]
> Anyway i'm not sure at the moment if your firmware uses PB1..4 oder PB0..3?
All 4 LEDs shoud blink on the startup. Afterward, only 3 are actualy used:
- PB1 - power on;
- PB3 - permit join mode;
- PB4 - ZNP events.
 I gues, you shoud check the connection of the PB4 LED.

**Comment by dimmu311** [comment]
> > Anyway i'm not sure at the moment if your firmware uses PB1..4 oder PB0..3?
> 
> All 4 LEDs shoud blink on the startup. Afterward, only 3 are actualy used:
> 
> * PB1 - power on;
> * PB3 - permit join mode;
> * PB4 - ZNP events.
> 
> I gues, you shoud check the connection of the PB4 LED.

Ok tank you. Now i see also PB4 light up at startup. But the time is shorter than the other 3.
So i'm very new to ZStack. 
permit join mode means the stick is ready for pairing new devices?
ZNP Event is sending or receiving zigbee telegramm?

**Comment by reverieline** [comment]
> permit join mode means the stick is ready for pairing new devices?

Correct.



> ZNP Event is sending or receiving zigbee telegramm?

Any RF or serial port communication.

**Comment by dimmu311** [comment]
ok, now i got it.
Realy nice work. tank you
