### ISSUE TITLE
Firmware for MODKAMRU Zigbee V3 USB stick included 4 LEDs

### ISSUE THREAD

**Issue by zslibra** [reverieline/CC2538-CC2592-ZNP#4]
Hello reverieline,
I am trying to assemble a USB stick using CC2538+2592 (MODKAMRU Zigbee V3 USB stick included 4 LEDs) for coordinator.
I have downloaded 3 different firmware:
MODKAMRU_V3_UART-flow-control.hex, MODKAMRU_V3_UART-no-flow-control.hex, MODKAMRU_V3_USB.hex
Which firmware should I use for zigbee2mqtt?
Do I need the firmware in the following location?
https://github.com/reverieline/CC2538-CC2592-ZNP/tree/master/MODKAMRU_V3/alt_layouts
Thank you.

**Comment by reverieline** [comment]
@zslibra Hi! 
All of the listed builds are compatible with zigbee2mqtt. The only difference is interfacing type and LED layout. 
If you are building the device by modkam.ru schematic and going to use USB connection,  then MODKAMRU_V3_USB.hex is the one you need.

**Comment by zslibra** [comment]
hello reverieline,
understood.
thanks for your quick reply and nice work!

**Comment by reverieline** [comment]
> 
> 
> hello reverieline,one more question,
> LEDs is not activated in firmware MODKAMRU_V3_USB.hex, but the LED is activated in firmware
> MODKAMRU_V3_USB-devboard-v1.hex?
> Is my understanding correct?
> Thanks.

All MODKAM* builds support LEDs. 
*devboard-v1.hex  is for alternative dev boards  that use PC4-7 pints for LEDs. Like this one: https://aliexpress.com/item/4000522367679.html

**Comment by zslibra** [comment]
I see.
Thanks reverieline.
