### ISSUE TITLE
ZNP fw MODKAMRU_V3_UART-no-flow-control

### ISSUE THREAD

**Issue by Harwesta** [reverieline/CC2538-CC2592-ZNP#5]
Please add uart mode description to the readme file.
What a UART mode used in the firmware (baud rates, start/stop bits)?
**MODKAMRU_V3_UART-no-flow-control** - use xon/xoff only? 
**MODKAMRU_V3_UART-flow-control.hex** - use a hardware RTS / CTS flow control ?

I flashed the module with _MODKAMRU_V3_UART-no-flow-control.hex_ and connected it to ttyS1 uart port (115200 8N1, 230400 8N1), but the zigbee2mqtt does not detected.

**Comment by reverieline** [comment]
> 
> 
> Please add uart mode description to the readme file.
> What a UART mode used in the firmware (baud rates, start/stop bits)?
> **MODKAMRU_V3_UART-no-flow-control** - use xon/xoff only?
> **MODKAMRU_V3_UART-flow-control.hex** - use a hardware RTS / CTS flow control ?
> 
> I flashed the module with _MODKAMRU_V3_UART-no-flow-control.hex_ and connected it to ttyS1 uart port (115200 8N1, 230400 8N1), but the zigbee2mqtt does not detected.

Try to disable flow control for z2m:
advanced:
  rtscts: false

**Comment by reverieline** [comment]
Serial port configuration:
{
	baudRate: 115200,
	rtscts: true, 
	dataBits: 8,
	stopBits: 1, 
	parity: 'none' 
}

Zigbee2mqtt related parameters:

advanced:
  baudrate: 115200
  rtscts: true
serial:
  port: /dev/ttyACM0

CTS pin should be pulled low if you don't connect it to RTS output on the host.

First device bootup takes about 30 seconds.

**Comment by Harwesta** [comment]
Thanks, i try it.

I think for _UART-no-flow-control_ valid parameters:
```
advanced:
  baudrate: 115200
  rtscts: false
serial:
  port: /dev/ttyS1
```

`port: /dev/ttyACM0`
Really ?
I think /dev/ttyACM0 used for UART-over-USB modes, for native UART connection between CC2538 and host must /dev/ttyS1.
On my stick CTS to GND isnt connections, but i think a _UART-no-flow-control_ firmware is not use CTS/RTS pins /scratch head/.

**Comment by Harwesta** [comment]
Valid settings zigbee2mqtt module for _MODKAMRU_V3_UART-no-flow-control_ firmware is
`
serial:
  port: /dev/ttyS1
advanced:
  baudrate: 115200
  rtscts: false
`
CTS/RTS pin is not used and not pullup/pulldow needed.

see log
`> zigbee2mqtt@1.8.0 start /zigbee2mqtt-1.8.0
> node index.js
zigbee2mqtt:info  2020-05-10 16:19:02: Logging to console and directory: '/share/zigbee2mqtt/log/2020-05-10.16-19-02'
zigbee2mqtt:info  2020-05-10 16:19:03: Starting zigbee2mqtt version 1.8.0 (commit #unknown)
zigbee2mqtt:info  2020-05-10 16:19:03: Starting zigbee-herdsman...
zigbee2mqtt:info  2020-05-10 16:19:48: zigbee-herdsman started
zigbee2mqtt:info  2020-05-10 16:19:48: Coordinator firmware version: '{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327}}'
zigbee2mqtt:info  2020-05-10 16:19:48: Currently 0 devices are joined:
zigbee2mqtt:warn  2020-05-10 16:19:48: `permit_join` set to  `true` in configuration.yaml.
zigbee2mqtt:warn  2020-05-10 16:19:48: Allowing new devices to join.
zigbee2mqtt:warn  2020-05-10 16:19:48: Set `permit_join` to `false` once you joined all devices.
zigbee2mqtt:info  2020-05-10 16:19:48: Zigbee: allowing new devices to join.
zigbee2mqtt:info  2020-05-10 16:19:48: Connecting to MQTT server at mqtt://core-mosquitto:1883
zigbee2mqtt:info  2020-05-10 16:19:50: Connected to MQTT server
zigbee2mqtt:info  2020-05-10 16:19:50: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt:info  2020-05-10 16:19:50: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.8.0","commit":"unknown","coordinator":{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327}},"log_level":"info","permit_join":true}'`

**Comment by reverieline** [comment]
> `port: /dev/ttyACM0`
> Really ?
> I think /dev/ttyACM0 used for UART-over-USB modes, for native UART connection between CC2538 and host must /dev/ttyS1.
> On my stick CTS to GND isnt connections, but i think a _UART-no-flow-control_ firmware is not use CTS/RTS pins /scratch head/.

You are correct. I have referenced default z2m settings related to serial port communication.
